### ISSUE TITLE
Create a markdown version?

### ISSUE THREAD

**Issue by rernst** [UMCUGenetics/guix-documentation#1]
Would it be possible to generate a markdown (maybe even call it README.md) version of the pdf / tex document? This makes it a bit easier to view the document via a web browser.

**Comment by roelj** [comment]
Great idea!  I quickly looked at Pandoc to do an automatic conversion, but that doesn't seem to be very fruitful.  I will further look into this this week.

**Comment by roelj** [comment]
Actually.. It already looks pretty good [the develop branch](https://github.com/UMCUGenetics/guix-documentation/blob/develop/guix-for-bioinformaticians.md).

WDYT?

**Comment by rernst** [comment]
Looks good! Maybe add a Readme with links to these documents?

**Comment by roelj** [comment]
I've added the README linking to the different documents.

Thanks for the suggestion!
